services:
  nginx:
    image: nginx:1.25.5
    ports:
      - "80:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - django
    networks:
      - backend

  mariadb:
    image: mariadb:11.3.2
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./mariadb/.env
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend

  django:
    build: ./django
    container_name: django
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./src:/code
      - ./static:/static
    expose:
      - "8001"
    env_file:
      - ./django/.env
    depends_on:
      - mariadb
    networks:
      - backend
networks:
  backend: